projectmovie/movie_app/urls.py
from django.urls import path
from . import views
app_name='movie_app'
urlpatterns=[
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.movie_add,name='movie_add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')


]

projectmovie/project_movie/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie_app.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

projectmovie/movie_app/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')
    #                       height_filed='image_height', width_field='image_width')
    # image_height=models.PositiveIntegerField(null=True,blank=True, editable=False,default='100')
    # image_width=models.PositiveIntegerField(null=True,blank=True, editable=False,default='100')
    def __str__(self):
        return self.name

projectmovie/movie_app/forms.py
from django import forms
from . models import Movie
class Movieform(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

projectmovie/movie_app/views.py
from django.shortcuts import render, redirect
from .models import Movie
from django.http import HttpResponse
from . forms import Movieform

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render (request,'detail.html',{'movie':movie})
def movie_add(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')
def update(request,id):
    movie=Movie.objects.get(id=id)
    form=Movieform(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

projectmovie/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter the movie name">
    <input type="text" name="desc" placeholder="Enter the movie description">
    <input type="number" name="year" placeholder="Enter the year of release">
    <input type="file" name="img" width="100">
    <input type="submit">

</form>
{% endblock %}

projectmovie/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}


</body>
</html>

projectmovie/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post" >
    {% csrf_token %}
    Do you want to delete this movie?
    <input type="submit">

</form>
{% endblock %}

projectmovie/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row" style="display:flex; justify-content:space-around;">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" align="left" width="250" height="250">
        </div>
        <div class="col-md-6">
            <h6>{{movie.name}}</h6>
            <h4 align="left">{{movie.desc}}</h4>
            <h6>{{movie.year}}</h6>
            <a class= "btn btn-warning" href="{% url 'movie_app:update' movie.id %}">Update</a>
             <a class= "btn btn-danger" href="{% url 'movie_app:delete' movie.id %}">Delete</a>


        </div>


        </div>
</div>
{% endblock %}

projectmovie/templates/edit.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>
{% endblock %}

projectmovie/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row"
         >
        {% for i in movie_list %}
        <div class="col-md-3" ;>
            <div class="card" style="width: 18rem; height:520px; margin:10px; padding:20px;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="200px" height="200px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{%url 'movie_app:detail' i.id %}" class="btn btn-primary" style="align:bottom;">Show details</a>
      <a href="{%url 'movie_app:detail' i.id %}" class="btn btn-primary" style="align:bottom;">Add Movie </a>
  </div>
</div>

        </div>
         {% endfor %}
    </div>
</div>







{% endblock %}